### ISSUE TITLE
Compatible products page

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1166]
In the first phase of the redesign of this page, the aim will be to revamp the page using the new look and feel without introducing new functionality to the page. To this end, there will be 2 parts to this upgrade. The first of which is the compatible products section. In phase one, the standard Bootstrap 3 tabbed interface will be upgraded to use the new look and feel for the tab navigation. The navigation filter will be added as a separate feature in the post-launch phase of the redesign.

The actual tabbed content will also be changed to live in a borderless container rather than be constrained via a border around the elements of the container. Each of the products will then be put inside of a bordered, shadowless box with rounded corners, centered logo, name of the product, and the links associated below in a larger text. The additional dropdowns and button calls will be implemented as a separate issue in the post-launch phase.

The last section of this page is 2 centered floating text sections with a button, side by side under the compatible products section. These should be decently straightforward markdown content blobs, as there seem to be no fancy features associated.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585115
![image](https://user-images.githubusercontent.com/23018241/117980231-c23c4100-b301-11eb-9e01-863a9a37d874.png)

**Comment by ericpoirier** [comment]
Hi @shabnammayel,

I updated the layout of the Compatible products in the following staging page:
https://deploy-preview-1340--jakartaee.netlify.app/compatibility/

Note that the filter was not implemented. As discussed, I think this is a nice to have feature which we can add when we are in a better position with the overall redesign of the website.

Let me know if you have more questions.

Thanks.

**Comment by shabnammayel** [comment]
Hi Eric, when I choose the Jakarta Version the certification results dropdown is inactive and doesn't work and that's the case for the view certification button as well. Since the filter is not going to be implemented for now, can we have a search capability? given that this list is very long, at least that can help users search the product that they are looking for.

**Comment by ericpoirier** [comment]
> Hi Eric, when I choose the Jakarta Version the certification results dropdown is inactive and doesn't work and that's the case for the view certification button as well. Since the filter is not going to be implemented for now, can we have a search capability? given that this list is very long, at least that can help users search the product that they are looking for.

The options should be inactive for all the blocks except the one you're interacting with. I pushed a commit to my PR to make sure your browser is using the most recent version of the javascript code.

**Comment by ericpoirier** [comment]
Also to answer your question about the filter. We already have an issue which is classified as a nice to have:
https://github.com/jakartaee/jakarta.ee/issues/1173

I wouldn't want to create a temporary search for that page since we already plan on adding the filter.

**Comment by ericpoirier** [comment]
I asked @autumnfound and @linkfang to test this page and it is working as intended.

@shabnammayel can you verify that you don't have an ad blocker enabled in your browser?

Thanks.

**Comment by shabnammayel** [comment]
I don't but still doesn't work for me! I shared it with our team to test and it seems like it works for them. 

From looking at the page though, can you please change the word "Jakarta Version" to "Jakarta EE Version"? and "Certification Results" to "Server Version"? @ericpoirier

**Comment by ericpoirier** [comment]
> I don't but still doesn't work for me! I shared it with our team to test and it seems like it works for them.
> 
> From looking at the page though, can you please change the word "Jakarta Version" to "Jakarta EE Version"? and "Certification Results" to "Server Version"? @ericpoirier

Ok will do, after those text changes are we good to push this live?

**Comment by shabnammayel** [comment]
Would be great if @TanjaObradovic gets a chance to review again and give a +1 as well since I am not able to see! for some reason doesn't work on either of my 2 laptops! Also @excentrickristy please let us know if you see any issues as well! thanks

**Comment by ericpoirier** [comment]
> Would be great if @TanjaObradovic gets a chance to review again and give a +1 as well since I am not able to see! for some reason doesn't work on either of my 2 laptops!

Ok I will make the update and ping @TanjaObradovic to review.

**Comment by ericpoirier** [comment]
@TanjaObradovic I made the update requested by @shabnammayel. 

https://deploy-preview-1340--jakartaee.netlify.app/compatibility/

I'll wait for your +1 to merge.

Thanks.

**Comment by TanjaObradovic** [comment]
Thanks Eric! This works for me with no problems at all.

**Comment by excentrickristy** [comment]
@ericpoirier I was checking the header tags for this page and in the code its showing h2's from the table on this page https://deploy-preview-1340--jakartaee.netlify.app/compatibility/download/
Just wondering if this was originally coded for the view all link to just be a div hidden with css but now something has changed? If so, we should remove the content from the compatibility page.

Also, I think we need to promote "Latest TCK Results" and "View All" to an h2 and then wrap the company names in h3 tags.

Otherwise, this page looks and functions great!

**Comment by ericpoirier** [comment]
> @ericpoirier I was checking the header tags for this page and in the code its showing h2's from the table on this page https://deploy-preview-1340--jakartaee.netlify.app/compatibility/download/ Just wondering if this was originally coded for the view all link to just be a div hidden with css but now something has changed? If so, we should remove the content from the compatibility page.

Not sure what you mean here. Can you copy/paste or screenshot an example of what you are seeing?

> Also, I think we need to promote "Latest TCK Results" and "View All" to an h2 and then wrap the company names in h3 tags.

Here you would like me to convert the` <li>` tags into `<h2>` tags for the Latest TCK Results and View All navigation buttons?

**Comment by excentrickristy** [comment]
@ericpoirier So I was using my header checking tool and it found these h2 heading on the compatible products page:
![image](https://user-images.githubusercontent.com/73264129/144656314-9b0c2713-4016-42d9-8b61-14ff6c8e7853.png)

But this text isnt visible on the page.

So I looked at the source code and I see the table from the "view all" panel but when you click on "view all" it takes you to a different URL so I'm not sure if this table is still supposed to be embedded in this page:

![image](https://user-images.githubusercontent.com/73264129/144656508-bf6399d6-83a5-42fa-ba1f-1b30b68c6f28.png)

**Comment by ericpoirier** [comment]
Ok I see what you mean, its loading  the html of the "View All" page but its actually hidden from display. I'll make it so that the html doesnt load on that page.

**Comment by ericpoirier** [comment]
@excentrickristy I updated the html for both the Compatible Products page and the View All page

https://deploy-preview-1340--jakartaee.netlify.app/compatibility/

Let me know if there's anything else.

Thanks.

**Comment by excentrickristy** [comment]
@ericpoirier that did resolve the issue but it looks like this still needs to be done:

"Also, I think we need to promote "Latest TCK Results" and "View All" to an h2 and then wrap the company names in h3 tags."

@shabnammayel and I are discussing meta targeting for this page and I will provide new tags if necessary.

**Comment by ericpoirier** [comment]
> @ericpoirier that did resolve the issue but it looks like this still needs to be done:
> 
> "Also, I think we need to promote "Latest TCK Results" and "View All" to an h2 and then wrap the company names in h3 tags."
> 

How about we add invisible `<h2>` tags on those pages:

https://deploy-preview-1340--jakartaee.netlify.app/compatibility/
https://deploy-preview-1340--jakartaee.netlify.app/compatibility/download/

I would still add `<h3>` tags for the company names but by adding the invisible `<h2>` tags, we don't need to create special styles for this page's navigation.

Let me know if that works.

**Comment by ericpoirier** [comment]
@excentrickristy can you review the above changes?

Thanks.

**Comment by excentrickristy** [comment]
@ericpoirier unfortunately the hidden h2 doesn't work for accessibility. I know it's a pain :/

**Comment by ericpoirier** [comment]
@excentrickristy I updated the Compatibility products sections with your recommendation of using the h2 tags for the navigation links.

https://deploy-preview-1340--jakartaee.netlify.app/compatibility/
https://deploy-preview-1340--jakartaee.netlify.app/compatibility/download/

Let me know if there's anytyhing else.

Thanks.

**Comment by shabnammayel** [comment]
@ericpoirier we need to change the work TCK results to PRODUCT VERSION(S) (click to download) for this page https://deploy-preview-1340--jakartaee.netlify.app/compatibility/download/

To comply with trademark guidelines we created that download page and have to show the link to a downloadable product. the links seem to be right, it's the wording that should change.

**Comment by ericpoirier** [comment]
> @ericpoirier we need to change the work TCK results to PRODUCT VERSION(S) (click to download) for this page https://deploy-preview-1340--jakartaee.netlify.app/compatibility/download/
> 
> To comply with trademark guidelines we created that download page and have to show the link to a downloadable product. the links seem to be right, it's the wording that should change.

@shabnammayel Do you mean the TCK Results in the blue bar in the table or in the navitgations buttons section or both?

**Comment by shabnammayel** [comment]
The ones in the blue bar in the table @ericpoirier thanks

**Comment by ericpoirier** [comment]
> The ones in the blue bar in the table @ericpoirier thanks

I updated the title in the blue bar.

https://deploy-preview-1340--jakartaee.netlify.app/compatibility/download/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
Thanks, LGTM! but looking at the mockup, the text for the get listed and compatibility request buttons at the bottom of the page is missing please add below title: 
Get Listed: Find out how to get your product listed on the Compatible Products page
Compatibility Request: File a Certification Request with a specification project in the GitHub repository

**Comment by ericpoirier** [comment]
> Thanks, LGTM! but looking at the mockup, the text for the get listed and compatibility request buttons at the bottom of the page is missing please add below title: Get Listed: Find out how to get your product listed on the Compatible Products page Compatibility Request: File a Certification Request with a specification project in the GitHub repository

I updated the content of the blocks at the bottom.

https://deploy-preview-1340--jakartaee.netlify.app/compatibility/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
LGTM! thanks @ericpoirier

**Comment by shabnammayel** [comment]
@ericpoirier please don't move forward with this page yet. We noticed that the new design is ignoring the full list of products, Full Platform and Web Profile. I reached out to @excentrickristy  to see if it's something that we have missed in the design. If that's the case, we need to come up with a solution to properly show case the full list. thanks

**Comment by shabnammayel** [comment]
Hi @ericpoirier for the compatibility page please change the design to the following:

Tab 1: (is the current tap that we have live on the website)
 https://invis.io/AX10M9QL74RN#/462294357_Compatibility_Tab_1

Tab 2: after testing the implemented tab, we decided to change the design to this format. Please change the title in the table to "CERTIFICATION RESULTS". In the mock up it is certification. 
https://invis.io/AX10M9QL74RN#/462294355_Compatibility_Tab_2

**Comment by excentrickristy** [comment]
Link to design files: https://www.dropbox.com/s/2hzszsowkimzhu6/Jakarta-Design-4Drev2.ai?dl=0

**Comment by ericpoirier** [comment]
Shabnam and I had a quick call to discuss the changes requested and here are some clarifications to what needs to be done:

Tab 1:

- [x] Use bordered boxes with each items to tie in with the design of other pages
- [x] Add link to each logos (We should use the Download url)

Tab 2:

- [x] - Add logos to current table
- [x] - Certification Results links needs to be on their separate lines
- [x] - Use the links labeled "Compatibility" in the data file
- [x] - The links needs to be blue
- [x] - Add a sidebar containing links for each releases
- [x] - Each releases should be displayed on their separate page for better SEO (requested by Kristy)

**Comment by ericpoirier** [comment]
@shabnammayel you can find an updated version of the Compatible products page on the following staging page:
https://deploy-preview-1372--jakartaee.netlify.app/compatibility/

Let me know if everthing is what you expected.

Thanks.

**Comment by shabnammayel** [comment]
I have added my comments on this issue https://github.com/jakartaee/jakarta.ee/issues/1167 thanks
