### ISSUE TITLE
Implement the new Jakarta EE website homepage 

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#2240]
As discussed on the call today, please find the Figma files here: 

https://www.figma.com/design/2KewKkyuXUqa8DzBoW9rBN/SHARED_Jakarta-EE-New-Branding-AUG-19-2025?node-id=2219-1394&p=f&t=DSQtAYm8wMXCRKsv-0

I am tagging @excentrickristy here in case you need any additional assets for the designs for implementation

Thanks

**Comment by autumnfound** [comment]
Hi all, just some follow up questions that @gnugomez and I had after spending some time looking through the Figma design.

1. For the nav menu, what is the intention with mobile view of the menu? Do we want to use the normal functionality with collapsible menu items, or is there some other design/functionality intended for the menu at mobile and tablet views?
1. Additional question for the nav menu. In the expanded views of the nav menus, there is a white banner/background under the header, but in other views that banner is not there. Is that an older design element that was left after reworks of the main page, or is there some intended functionality to make that banner appear in some situation?
1. For the GitHub contributor section, we just want to confirm that the profile bubbles are static, or if not what is the intention behind that, as it's hard to convey in a static design. As an additional followup, what is the plan for smaller than desktop views? The floating profile pictures would likely be very cluttered on anything less than desktop, so do we want to keep that as a sort of flair for normal desktop view and just have a standard banner section in those breakpoints?
1. For the testimonials section under Join Us, what is the intended display here? Is the intent for it to be edge to edge? Do we want manual scrolling, a slow slide to loop the testimonials, or something else?
1. For the sticky footer, do we intend to force the user to have the expanded view in the corner at all times after initial scroll? That seems like it might block some content and might impede the user experience if we don't have way of collapsing it back down to the initial view, such as a little collapse arrow.
1. Regarding the cookie consent banner, right now it remains the solid grey banner with orange buttons which somewhat clash with the new design, and there doesn't appear to be an alternative design provided in the Figma files. Jordi had a good suggestion of using the new cookie consent banner that is being created for the new EF look and feel we are currently implementing. I don't know where he pulled the design screenshots from, though. Jordi, could you post a screenshot of the new version so we can get see if that would work with the resdesign?

Also, Jordi may have more questions WRT the design elements than I do, so he may follow up with more questions in the next day.

**Comment by shabnammayel** [comment]
1. For the nav menu, what is the intention with mobile view of the menu? Do we want to use the normal functionality with collapsible menu items, or is there some other design/functionality intended for the menu at mobile and tablet views?
**Will work with Excentric to get a mobile view.**
2. Additional question for the nav menu. In the expanded views of the nav menus, there is a white banner/background under the header, but in other views that banner is not there. Is that an older design element that was left after reworks of the main page, or is there some intended functionality to make that banner appear in some situation?
**As soon as you scroll down the white bar appears behind the nav and the nav area becomes a sticky menu**

3. For the GitHub contributor section, we just want to confirm that the profile bubbles are static, or if not what is the intention behind that, as it's hard to convey in a static design. As an additional followup, what is the plan for smaller than desktop views? The floating profile pictures would likely be very cluttered on anything less than desktop, so do we want to keep that as a sort of flair for normal desktop view and just have a standard banner section in those breakpoints?
**I think we should add subtle animation/cycling so instead of waiting for a full page refresh, fade or slide in new faces every few seconds so the variety is clear.
And we can add a larger group cluster to how more than six at once (maybe 10–12) in a scattered, organic layout. That immediately signals scale and feels more like a community. I'll see if we can get a mobile view**
4. For the testimonials section under Join Us, what is the intended display here? Is the intent for it to be edge to edge? Do we want manual scrolling, a slow slide to loop the testimonials, or something else?
**The testimonials automatically slide from right to left as the person scrolls. The left side only bleeds edge to edge upon scrolling. I think I added an example in the Figma file for that section**

5. For the sticky footer, do we intend to force the user to have the expanded view in the corner at all times after initial scroll? That seems like it might block some content and might impede the user experience if we don't have way of collapsing it back down to the initial view, such as a little collapse arrow.
**You could add an X in the corner or just click it to expand/collapse which is common**

6. Regarding the cookie consent banner, right now it remains the solid grey banner with orange buttons which somewhat clash with the new design, and there doesn't appear to be an alternative design provided in the Figma files. Jordi had a good suggestion of using the new cookie consent banner that is being created for the new EF look and feel we are currently implementing. I don't know where he pulled the design screenshots from, though. Jordi, could you post a screenshot of the new version so we can get see if that would work with the resdesign?
**A screenshot would be helpful**

**Comment by gnugomez** [comment]
<img width="511" height="264" alt="Image" src="https://github.com/user-attachments/assets/71d345ac-bfcc-49e7-9964-7027fd88947d" />

@shabnammayel this is the new cookie banner we're going to implement for the eclipse.org redesign, do you think it makes sense to us to use it here as well?

**Comment by shabnammayel** [comment]
thanks for sharing @gnugomez LGTM!  but where is this going to be displayed on the page? is it going to be a pop up in the middle of the page or similar to the current one at the button of the page?

**Comment by gnugomez** [comment]
> thanks for sharing [@gnugomez](https://github.com/gnugomez) LGTM! but where is this going to be displayed on the page? is it going to be a pop up in the middle of the page or similar to the current one at the button of the page?

it will be the same behaviour, but with a different UI, floating on a corner of the screen

**Comment by gnugomez** [comment]
Hi @shabnammayel,

to make things a bit smoother, could you kindly add comments over all the menu links that should move you to another page, pointing to the page you should be moved to?

Cheers

**Comment by autumnfound** [comment]
I've created an issue to ensure that the start.jakarta.ee landing page remains consistent with the new look and feel. See https://github.com/eclipse-ee4j/starter/issues/368. Thanks for bringing that up @gnugomez !

**Comment by shabnammayel** [comment]
The item under the Developer portal in the navigation and changes we are proposing are outlined here: https://docs.google.com/document/d/12NSITxmOswPiRK5M-bCoasidj2Nq2lpe9AUEQa-PxfA/edit?tab=t.691dp9t9b46n

Please note that I'd like to remove "Jakarta EE" from the title of each the columns for example "Contribute to Jakarta EE" just change to "Contibute" so they will be Contribute, Develop and Learn

**Comment by gnugomez** [comment]
Hello @shabnammayel,

In order to gather early feedback, could you kindly go through the mega menu in this preview – https://deploy-preview-2285--jakartaee.netlify.app/?

Let me know if the menu links are correct according to the spreadsheet you shared. 

You can also take a look at the menu on mobile; it should be the same.

Please expect that things that aren’t the menu to be broken – that’s a WIP.

**Comment by shabnammayel** [comment]
Sounds good and thank you @gnugomez I'll review and add feedback.

I have the mockup us for the new "Join us" page as well as the "Developer portal" page here: https://www.figma.com/design/4aUN7rmqSHGiCMjuStYeaZ/Jakarta-EE?node-id=84-4035&t=TWuRjV89TQuF885k-0

The developer portal page still requires minor tweaks as you see my comments in the file but the Join us page is ready for implementation. thanks

**Comment by autumnfound** [comment]
> Sounds good and thank you [@gnugomez](https://github.com/gnugomez) I'll review and add feedback.
> 
> I have the mockup us for the new "Join us" page as well as the "Developer portal" page here: https://www.figma.com/design/4aUN7rmqSHGiCMjuStYeaZ/Jakarta-EE?node-id=84-4035&t=TWuRjV89TQuF885k-0
> 
> The developer portal page still requires minor tweaks as you see my comments in the file but the Join us page is ready for implementation. thanks

Thanks Shabnam! Please note that for Q4, we will be only implementing the home page and ensuring that the overall look and feel with the new theme doesn't break any of the current pages. These pages will be implemented in the new year when we start to tackle the rest of the site.

**Comment by shabnammayel** [comment]
Thanks so much for the preview @gnugomez my feedback below:

1. Inconsistent Capitalization / Sentence Case

- Several menu items appear in Title Case instead of the agreed sentence case (e.g., “How to guides,” “Learning hub,” “Stay Connected,” “Product certification results”).

Please review all headings and sub-items to ensure:

- Headings remain Title Case (e.g., “Community Content”)

- All menu items under each heading use sentence case (e.g., “How to get involved,” “Stay connected,” “How to contribute,” “Get started,” etc.).

Right now capitalization is inconsistent across the menus.

2. Line Breaks / Items Wrapping to a Second Line

- Items with two or more words are wrapping to a second line in several menus (“Insights and publications,” “Product certification results,” etc.).

- All menu items should fit on a single line. It improves readability and keeps the menu visually balanced.

3. Missing Icons in All Mega Menus

In the Specifications mega menu, icons are present (“Explore specifications,” “Releases,” “Additional resources”), but in the Developer Portal, Community, About, and Join Us menus, icons are missing.

For each column heading please include its icon, as originally designed.

4. Compatible Products Menu

- Current ordering feels visually odd because “Get listed” is sandwiched awkwardly between “Jakarta EE compatible products” and “Product certification results.”

Recommendation:

- Move “Get listed” to the bottom of the list to create a cleaner hierarchy:

Jakarta EE compatible products

Product certification results

Get listed

- Also this dropdown doesn't have a column heading. To align with all other mega menus, please add a title "Compatibility" on top

5. Vertical Divider Alignment

- In some menus, the vertical divider appears slightly off-center relative to column content.

- Please check alignment so that:

The dividers are perfectly centered between the two columns they separate.

Vertical spacing is consistent above and below divider lines.

Example: 
The vertical divider between Explore specifications and Releases is shifted slightly to the right, making the left column look wider than the right.

The divider also appears slightly lower compared to the text above it, creating uneven vertical spacing.

6. Uneven Column Widths / Balance

Some columns have many items (e.g., “Community Content”), while others have only one or two (“Take part”).

If possible, adjust column widths or spacing so that:

Columns look visually balanced.

Text columns do not feel crowded while others appear empty.

7. under join us dropdown, remove the "meet the contributors" item as that page doesn't exist yet.
8. Under Developer portal dropdown:
Add a CTA at the bottom: Explore the developer portal
The “explore the developer portal” CTA should be at the bottom in between two columns as we are finalising landing page for that. So we want the user to go to the full page and explore the full page. 
Change "How to contribute" there to "Contribution guide" to be more consistent with the rest of the namings in that column

**Comment by gnugomez** [comment]
Hello @shabnammayel, thank you for your feedback – I’m currently implementing it.

Regarding the icons for the mega menu, I apologize for not mentioning this previously. The plan was always to incorporate them, but at the time I shared the preview, I hadn’t indicated that they weren’t present.

Concerning the “Compatible products” dropdown, the design doesn’t currently include any titles, and I believe it works well as it is. Furthermore in mobile It wouldn’t make sense to add an extra step to open items when there are no other columns to differentiate them.

Regarding the CTA within the Developer portal dropdown between the columns, I’m unsure if there’s any design in place. Could you please share any resources that might clarify your intentions here?

Because this is what I understood from your description, and I don't think it works well here, it also brings up the problem of how to solve this in mobile...

<img width="1531" height="359" alt="Image" src="https://github.com/user-attachments/assets/d12488f2-8913-4db3-bf9c-1f0910195d28" />

**Comment by shabnammayel** [comment]
thanks for the explanation and mockup for the developer portal link @gnugomez 
Below is what I have in mind, let's not use the orange button and keep it the same font color as other items in the menu. But maybe introduce a small arrow “→”:

<img width="505" height="159" alt="Image" src="https://github.com/user-attachments/assets/bcb2c965-0c60-4f97-8199-678e97d8b3c7" />
And go sentence case everywhere :)

**Comment by gnugomez** [comment]
@shabnammayel given that there's no desing for the join us mega menu, do we have any icons for the columns?

**Comment by autumnfound** [comment]
@shabnammayel I've sent a message to the folks maintaining the Jakarta.ee starter site at https://start.jakarta.ee/ in the issue https://github.com/eclipse-ee4j/starter/issues/368 regarding the redesign. As the starter uses the current style of page, they'll need to update base styles to align with the rest of our content. They requested a new design for their home page in figma for the update.

cc @kito99

**Comment by gnugomez** [comment]
@shabnammayel we have an issue with this section 

<img width="861" height="588" alt="Image" src="https://github.com/user-attachments/assets/7e968e53-37f6-4ccd-87c2-5002f6343367" />

The thumbnail images that are shown in the design should be uploaded in the newsroom if we want to display them, also since the image is optional we have to come up with a fallback image for those events that don't have an image.

**Comment by gnugomez** [comment]
@shabnammayel Do you have a list with all the testimonials that we want to display here?

<img width="911" height="404" alt="Image" src="https://github.com/user-attachments/assets/2040bb50-20f8-4bc1-8acb-6c83336429ee" />

This looks to me to be a horizontal scroll area, but at the same time we only have two entries (the third doesn't even have text).

**Comment by gnugomez** [comment]
@shabnammayel could you specify either by using comments in the figma or using a spreadsheet, the expected actions of the homepage buttons? thanks in advanced!

**Comment by shabnammayel** [comment]
@gnugomez The data for all the quotes/testimonials is already on the current website, can you use those and update the styling? I believe we have one for each of the strategic members, so total of five and yes it's going to be a horizontal scroll. thanks

**Comment by gnugomez** [comment]
@shabnammayel that makes perfect sense! just asking bc the ones on the desing looked a bit different from the ones we have.

**Comment by gnugomez** [comment]
Hey @shabnammayel,
I understand you may be busy with Jakartaone. Please consider this information at your earliest convenience.

We’ve finalised the implementation of the designs initially shared. You can view a preview here: https://deploy-preview-2304--jakartaee.netlify.app/. We would greatly appreciate any feedback you can provide.

Regarding the developer portal we discussed, I’m unsure how best to implement this. I’m also considering the mobile version of the menu, particularly given your ongoing work with the design agency. Do you think they could incorporate this into the overall design?

We’ve identified some contrast issues within the _News & Announcements_ section; the outline buttons lack sufficient contrast against the background on mobile. We need to resolve this. One option is to adjust the background position, but we must ensure this doesn’t impact other areas utilising similar buttons and gradient backgrounds.

Also you'll notice that some links are missing and most likely some others won't take you to where you were expecting to, so I will appreciate if you can share the link/action that you're expecting to happen when a user clicks on each button/link/card.

Cheers,

**Comment by shabnammayel** [comment]
> [@shabnammayel](https://github.com/shabnammayel) could you specify either by using comments in the figma or using a spreadsheet, the expected actions of the homepage buttons? thanks in advanced!

@gnugomez I am not able to tag you in the figma file! The agency provided the updated mockups based on my feedback. They are labelled in the figma file menu as Dec 1. We have Livestream today and am traveling tomorrow so I won't be able to be much  more helpful until Thursday probably:)

**Comment by shabnammayel** [comment]
The agency had also created a mobile version of the menu, it's in the same Figma file under "Updated" in the menu here: https://www.figma.com/design/2KewKkyuXUqa8DzBoW9rBN/SHARED_Jakarta-EE-New-Branding-AUG-19-2025?node-id=2590-2068&p=f&t=f8fXQmG69IiPwe75-0 @gnugomez

**Comment by autumnfound** [comment]
@shabnammayel, @gnugomez has gotten through the initial round of feedback for the updates to the site, as well as most of the mobile menu updates. You can see these updates on the stable redesign preview: https://redesign-2025--jakartaee.netlify.app/

Jordi, it looks like the only thing missing from the mobile menu is that some of the secondary nav links are anchored to the top of the mobile menu across all of the different modals/screens.

**Comment by shabnammayel** [comment]
Banner main CTA Links:

Join us: We want to link to this new page that we created [a mock up for here](https://www.figma.com/design/4aUN7rmqSHGiCMjuStYeaZ/Jakarta-EE?node-id=84-3511&p=f&t=dGPtM5BPn3haSvGx-0). but if it can't be implemented by the time we go live with the new branding, for now it can be linked to the "become a member" page here for now:  https://jakarta.ee/membership/ 

Latest Release: https://jakarta.ee/release/11/

CTA Links for the box items in the banner:

Learn about mentorship: https://jakarta.ee/mentorship/
Explore the learning hub: https://jakarta.ee/learn/
Get started: https://start.jakarta.ee/

down on the page CTA links: 

Contribute to Jakarta EE: https://jakarta.ee/contribute/

View all releases: https://jakarta.ee/release/

View specifications: https://jakarta.ee/specifications/

Get involved (at the bottom): idea is to go to "Join us" page: https://www.figma.com/design/4aUN7rmqSHGiCMjuStYeaZ/Jakarta-EE?node-id=84-3511&p=f&t=dGPtM5BPn3haSvGx-0 but if not implemented by the time we go live, we should hide this button for now

View all members: https://jakarta.ee/membership/members/

**Comment by shabnammayel** [comment]
For the "Why Jakarta EE" section, I had added an example if Figma to showcase how the boxes are supposed to function (roll up as we scroll down). please see example here: https://defygravitycampaign.utoronto.ca/ in the "discover our campaign priorities" section

**Comment by shabnammayel** [comment]
Please also see the updates they made  "1 Dec version" to some of the CTAs in the menu bar and the hero section as we discussed previously

<img width="1091" height="387" alt="Image" src="https://github.com/user-attachments/assets/c1e55929-33cb-47f8-b9d4-af983efe4c70" />

**Comment by shabnammayel** [comment]
Regarding the developer portal, I am not sure what the question/problem is. Do we need to have a call to discuss that section? thanks @gnugomez and @autumnfound

**Comment by shabnammayel** [comment]
I see that the two buttons below both go to the same page based on the current website: https://jakarta.ee/news/

<img width="631" height="145" alt="Image" src="https://github.com/user-attachments/assets/353400d1-72c4-4540-9e0d-9773d4fbc9e2" />
So let's remove the blue button and keep the orange one but rename it to: View all

**Comment by autumnfound** [comment]
For secondary megamenu links: We are removing all but My Account and Selected language dropdown, and we want to switch the `My Account` item to be a standalone icon with a dropdown, like on Eclipse.org with the same links.

For the download CTA we want to use some top margin to make the text more inline with the menu text.

For the `View all specifications`, the button should trigger a modal that pops up to show the specification diagram with clickable sections which should lead to the latest version of the given specification.

For the jumbotron, we are missing the rotating text for the orange text. We want to rotate the images through a few stock photos.

**Comment by shabnammayel** [comment]
Please change the "Get started" to "Join us" on the button next to latest release here (based on 1 Dec mockup in Figma): 
<img width="704" height="172" alt="Image" src="https://github.com/user-attachments/assets/35890981-ead8-4522-a636-f9852405ca83" />
Thanks

**Comment by shabnammayel** [comment]
For the events section, we need an orange CTA button with white font "View all events" that goes to this page: https://jakarta.ee/community/events/ 
It can be added at the bottom of the box thanks

**Comment by shabnammayel** [comment]
I noticed that the implementation of the featured story as a sticky note is also missing. I presented it during our initial walkthrough meeting as well and there were no concerns, just making sure it's not falling off the rador. 

<img width="1067" height="585" alt="Image" src="https://github.com/user-attachments/assets/fb7744f8-1514-4b6f-b2a1-a5255bd3c584" />

**Comment by autumnfound** [comment]
@shabnammayel for the smaller content updates to the CTAs and link updates, I've made a patch that covers all of them here: https://deploy-preview-2313--jakartaee.netlify.app/. This means that we have the items I listed in my previous comment + the featured story sticky note style left to implement.

**Comment by autumnfound** [comment]
@shabnammayel can you take a look at the high value subpages to confirm we haven't missed any broken functionality? I've taken a look at a majority of the pages and I believe at this point we've gotten the pages all functional. I'm going to be making a small patch to https://redesign-2025--jakartaee.netlify.app/about/working-group/ to address a few small bugs that make the page look less optimal as it's one of the high value landing pages.

**Comment by shabnammayel** [comment]
Thanks @autumnfound. Can we please adjust the box elements and icons to look as close to the mock-up:

<img width="831" height="172" alt="Image" src="https://github.com/user-attachments/assets/2c63adc3-0dcf-49ba-b064-4918780eadd9" />
also please add a + to the specification CTA so it's clear it's a toggle that can expand and include the specification image?
<img width="538" height="212" alt="Image" src="https://github.com/user-attachments/assets/57ce0b00-0098-4c10-b1ab-d0280cfe0e91" />
And I think it's better to add the view all events CTA in the box somewhere around where I highlighted below:

<img width="1322" height="462" alt="Image" src="https://github.com/user-attachments/assets/8f60430f-8839-4055-8851-5d26aa51002d" />
And also please remove these from the upper menus as discussed. thanks
<img width="520" height="71" alt="Image" src="https://github.com/user-attachments/assets/3d0d5e59-4c54-4e25-b6f6-6a05de190add" />

**Comment by shabnammayel** [comment]
Actually, for the events CTA, let's follow the mockup below: 

<img width="604" height="290" alt="Image" src="https://github.com/user-attachments/assets/548c460d-3369-40f1-a8f7-00162bc71886" />

**Comment by autumnfound** [comment]
> Actually, for the events CTA, let's follow the mockup below:

I see that that was put into the updated mock, which wasn't caught as it wasn't explicitly raised. I can make the update to match that change today

> Can we please adjust the box elements and icons to look as close to the mock-up:

This was addressed yesterday and merged earlier this morning, you should be able to see that on the main redesign link now!

> also please add a + to the specification CTA so it's clear it's a toggle that can expand and include the specification image? 

This is being handled and is currently up for review, see https://deploy-preview-2317--jakartaee.netlify.app/ for the preview. This is not an image, but accessible text with clickable buttons leading to each section!

**Comment by shabnammayel** [comment]
Is this the main design link?  https://deploy-preview-2317--jakartaee.netlify.app/ if so I still don't see the icons' alignment fixed in the box on the banner.

**Comment by autumnfound** [comment]
> Is this the main design link? https://deploy-preview-2317--jakartaee.netlify.app/ if so I still don't see the icons' alignment fixed in the box on the banner.

No, the main redesign link is https://redesign-2025--jakartaee.netlify.app/, which contains the icon alignment fix. The 2317 link I mentioned should solely be used if you want to see the specification section.

**Comment by shabnammayel** [comment]
The icons still look the same and are not aligned in the main design:

<img width="1353" height="699" alt="Image" src="https://github.com/user-attachments/assets/578d8abb-2e6d-41cc-bc4f-6b84fea66671" />

**Comment by autumnfound** [comment]
> The icons still look the same and are not aligned in the main design:

The icons match the icon bar as stated in v17 of the design. Should I target an earlier version instead?

<img width="1098" height="183" alt="Image" src="https://github.com/user-attachments/assets/45cb3b00-5870-4faa-a884-48a276d50cef" />

**Comment by autumnfound** [comment]
@shabnammayel for the bottom right corner popup, did we want that to be dynamic? If we want to be dynamic, there's no icon that's included in newsroom, so we wouldn't be able to include an updating automatic icon.

**Comment by shabnammayel** [comment]
The latest release button in the banner still goes to the wrong page, it should go to: Latest Release: https://jakarta.ee/release/11/

**Comment by gnugomez** [comment]
Hello @shabnammayel ,

I’m currently working on the featured story banner and have some concerns regarding it. Firstly, we don’t currently support icons within featured stories. Secondly, the implementation of this popup on mobile feels somewhat intrusive, as directly translating the sticky tab from desktop covers the entire screen. Could you provide an approximate mobile mockup, please?

**Comment by gnugomez** [comment]
Here's what I've implemented for now in regards to the "Featured Story", in mobile is hidden for now – https://deploy-preview-2324--jakartaee.netlify.app/

**Comment by trulymobilenwp** [comment]
@shabnammayel I am a bit concerned with the wording of the tagline on the main page under the changing title. It says 
"Develop, run, and scale enterprise Java apps in the cloud,
with the flexibility of open source technology"

To me this may imply we are supporting cloud only, which would alienate some users who work on premise. I suggest we could do the following:
"Develop, run, and scale enterprise Java apps anywhere,
with the flexibility of open source technology"

**Comment by shabnammayel** [comment]
Some minor feedback:
* some links in the menu should open in a new tab if they're taking us to another site (ie Jakarta One
* In the "community powered innovation" section, it's a bit hard to read the button text when it's not on hover
* The "play" button in the youtube section goes to the top of the page, it should go to Jakarta EE YouTube Channel: [www.youtube.com/@JakartaEE](http://www.youtube.com/@JakartaEE)
* footer text is all title case when the header megamenu links are sentence case
* The rotation between the keywords animated in the banner is a bit too slow, can we speed it up slightly?

**Comment by shabnammayel** [comment]
> Here's what I've implemented for now in regards to the "Featured Story", in mobile is hidden for now – https://deploy-preview-2324--jakartaee.netlify.app/

Thanks @gnugomez this is not including all the updates that were requested previously right? Cuz I still see the events CTA not changed, the link to Releases CTA in the banner is still wrong, etc.

**Comment by shabnammayel** [comment]
not on the mockup but I realise on the mobile view, it can easily be missed the the menu bar has a dropdown, can we add this icon next to the items in the menu for the mobile version? @gnugomez  

<img width="80" height="29" alt="Image" src="https://github.com/user-attachments/assets/48fb7249-6a56-476a-b714-271a520aaba4" />

**Comment by shabnammayel** [comment]
> [@shabnammayel](https://github.com/shabnammayel) I am a bit concerned with the wording of the tagline on the main page under the changing title. It says "Develop, run, and scale enterprise Java apps in the cloud, with the flexibility of open source technology"
> 
> To me this may imply we are supporting cloud only, which would alienate some users who work on premise. I suggest we could do the following: "Develop, run, and scale enterprise Java apps anywhere, with the flexibility of open source technology"

that's a good point @trulymobilenwp, @gnugomez can you please make that change? thanks

**Comment by autumnfound** [comment]
> - some links in the menu should open in a new tab if they're taking us to another site (ie Jakarta One
> - In the "community powered innovation" section, it's a bit hard to read the button text when it's not on hover
> - The "play" button in the youtube section goes to the top of the page, it should go to Jakarta EE YouTube Channel: [www.youtube.com/@JakartaEE](http://www.youtube.com/@JakartaEE)
> - footer text is all title case when the header megamenu links are sentence case
> - The rotation between the keywords animated in the banner is a bit too slow, can we speed it up slightly?

I've taken care of points 2, 3, and 5 in a PR.

**Comment by shabnammayel** [comment]
The Latest release link in banner still goes to the compatibility page instead of the EE 11 page. Please fix that @gnugomez and also I added [Developer advocate](https://jakarta.ee/community/developer-advocate/) under the Developer portal dropdown, can you please remove it from there and add it under the "Additional resources" under the community dropdown here: 

<img width="1295" height="386" alt="Image" src="https://github.com/user-attachments/assets/0fcd3fed-d31d-428c-a24a-df30a05b3945" />

**Comment by gnugomez** [comment]
Hey @shabnammayel, this is getting quite chaotic, would you mind creating a checklist either in this issue or in a separate doc where we can better understand what's left to be fixed and what's already done?

**Comment by shabnammayel** [comment]
> Hey [@shabnammayel](https://github.com/shabnammayel), this is getting quite chaotic, would you mind creating a checklist either in this issue or in a separate doc where we can better understand what's left to be fixed and what's already done?

Hi Jordi, I sent an invite for us to sync quickly today.

**Comment by shabnammayel** [comment]
@jph152 can you please share the link to the hubspot subscription form for the news section below: 

<img width="1186" height="510" alt="Image" src="https://github.com/user-attachments/assets/f2c7db6d-65bb-4065-893c-132f05201bda" />

**Comment by shabnammayel** [comment]
Checklist:
- Sticky note updates (popup+icon)
- The OG image is added for when we share the link: https://www.figma.com/design/2KewKkyuXUqa8DzBoW9rBN/SHARED_Jakarta-EE-New-Branding-AUG-19-2025?node-id=2731-4581&t=HcfXHyyhBWOX1LVL-1
- The submit news link should be updated
- Update the compatible products dropdown
- Update the "learning hub" icon: https://www.figma.com/design/2KewKkyuXUqa8DzBoW9rBN/SHARED_Jakarta-EE-New-Branding-AUG-19-2025?node-id=2731-4581&t=HcfXHyyhBWOX1LVL-1
- Update the footer to be sentence case (can be done after launch)
- Update the link on the Subscribe CTA once Jacob shares the link
- Update the title in the banner to become sentence case here: https://redesign-2025--jakartaee.netlify.app/supporters/sponsor/

**Comment by shabnammayel** [comment]
As discussed on the call @gnugomez , please add "enterprise" in below before Java in the banner, and remove it from rotation. Instead add "open source" in rotation in addition to the ones we have (vendor neutral, cloud native and scalable)

**Comment by jph152** [comment]
@shabnammayel here is the HubSpot form: https://share.hsforms.com/1Vn5cobvWQ2CdrC65FEia_A38167

**Comment by shabnammayel** [comment]
[Jakarta_WebsiteQA.pdf](https://github.com/user-attachments/files/24272639/Jakarta_WebsiteQA.pdf)]
@gnugomez please see the attached, comments from the agency's des,igner comparing the mockup to the implementation. thanks

**Comment by gnugomez** [comment]
hey @shabnammayel today I'm finishing up the last feedback you gave me, do we want to make it a blocker for the release this design agency's feedback? as far as I see is all related to text size/spacing and margins between things.

**Comment by shabnammayel** [comment]
that's great @gnugomez no let's not delay the release! If you can incorporate their feedback before the launch, that would be great! otherwise let's launch as planned and incorporate them after. thanks

**Comment by gnugomez** [comment]
thanks @shabnammayel, I'll try to squish it in, but I'm not sure I'll have time since tomorrow is my last day.

**Comment by gnugomez** [comment]
Here I have a preview of the latest changes you requested – https://deploy-preview-2344--jakartaee.netlify.app/

**Comment by shabnammayel** [comment]
> Here I have a preview of the latest changes you requested – https://deploy-preview-2344--jakartaee.netlify.app/

Looks very good! thanks so much @gnugomez

**Comment by shabnammayel** [comment]
@gnugomez/ @oliviergoulet5 and @autumnfound The design team has updated the branding guidelines here and we should replace it on the website: 

[Jakarta-ee-branding-guidelines.pptx.pdf](https://github.com/user-attachments/files/24454413/Jakarta-ee-branding-guidelines.pptx.pdf)

It's currently mentioned on this page: https://jakarta.ee/legal/trademark_guidelines/ and here: https://jakarta.ee/resources/ but there might be more pages that mention the guidelines and need to be updated.

**Comment by shabnammayel** [comment]
Congrats and thank you @gnugomez and @autumnfound for the new website! 

I am looking at the banner, is there two spaces between the rotating words and enterprise? if yes,can you please remove one?

<img width="1158" height="259" alt="Image" src="https://github.com/user-attachments/assets/473587bb-b597-4619-a031-90cc3c741b2d" />

**Comment by autumnfound** [comment]
> I am looking at the banner, is there two spaces between the rotating words and enterprise? if yes,can you please remove one?

There's no literal space, this seems to be some weird interaction with the letter spacing and the animation. I'm going to split this off as it's own issue!

**Comment by autumnfound** [comment]
Other than the above mentioned issue which has had a separate issue created, I believe we are good to close this issue! The rest of the redesign has been split into per-page issues so that we can better manage conversations, and this issue was meant to cover the initial phase of work for the homepage updates. Is there anything else we need for the homepage @shabnammayel, or should we close this issue?

**Comment by shabnammayel** [comment]
@gnugomez  The design agency has provided some mockup options for the mobile version of the featured story in Figma (version 1 Dec): https://www.figma.com/design/2KewKkyuXUqa8DzBoW9rBN/SHARED_Jakarta-EE-New-Branding-AUG-19-2025?node-id=2590-2068&p=f&t=V6MDNrby5fb86PH0-0
I like this one better: 

<img width="368" height="479" alt="Image" src="https://github.com/user-attachments/assets/bef28a69-b9b3-4ce1-84ca-2abf4581f552" />

We can still go with what we discussed previously to add it above the navigation bar (for mobile only) if you still think that's a better option

cc @autumnfound

**Comment by shabnammayel** [comment]
@gnugomez I noticed we have Red hat's quote on the home page and also mention them in the our members section:
Please remove their quote from here since they are no longer a member:

<img width="1121" height="622" alt="Image" src="https://github.com/user-attachments/assets/dc1d139e-4525-4646-a558-8ee4bb9248ec" />

And also from the sentence below: 

<img width="1036" height="413" alt="Image" src="https://github.com/user-attachments/assets/3d1ca3a0-df49-4a26-bda1-131fa766aca1" />

Instead we should add Payara in the text. thanks
